// Manually import all Vuex modules since esbuild doesn't support require.context
import * as account from './account.js';
import * as agency from './agency.js';
import * as announcement from './announcement.js';
import * as auth from './auth.js';
import * as autoResponse from './auto_response.js';
import * as broadcast from './broadcast.js';
import * as channel from './channel.js';
import * as client from './client.js';
import * as flexMessage from './flexMessage.js';
import * as flexMessageAlt from './flex_message.js';
import * as friend from './friend.js';
import * as global from './global.js';
import * as home from './home.js';
import * as media from './media.js';
import * as precheckin from './precheckin.js';
import * as preview from './preview.js';
import * as reminder from './reminder.js';
import * as reservation from './reservation.js';
import * as review from './review.js';
import * as richmenu from './richmenu.js';
import * as scenario from './scenario.js';
import * as scenarioMessage from './scenario_message.js';
import * as setting from './setting.js';
import * as site from './site.js';
import * as staff from './staff.js';
import * as streamRoute from './stream_route.js';
import * as survey from './survey.js';
import * as system from './system.js';
import * as tag from './tag.js';
import * as template from './template.js';
import * as user from './user.js';
import * as variable from './variable.js';

// Export all modules with namespacing
export default {
  account: { namespaced: true, ...account },
  agency: { namespaced: true, ...agency },
  announcement: { namespaced: true, ...announcement },
  auth: { namespaced: true, ...auth },
  autoResponse: { namespaced: true, ...autoResponse },
  broadcast: { namespaced: true, ...broadcast },
  channel: { namespaced: true, ...channel },
  client: { namespaced: true, ...client },
  flexMessage: { namespaced: true, ...flexMessage },
  flexMessageAlt: { namespaced: true, ...flexMessageAlt },
  friend: { namespaced: true, ...friend },
  global: { namespaced: true, ...global },
  home: { namespaced: true, ...home },
  media: { namespaced: true, ...media },
  precheckin: { namespaced: true, ...precheckin },
  preview: { namespaced: true, ...preview },
  reminder: { namespaced: true, ...reminder },
  reservation: { namespaced: true, ...reservation },
  review: { namespaced: true, ...review },
  richmenu: { namespaced: true, ...richmenu },
  scenario: { namespaced: true, ...scenario },
  scenarioMessage: { namespaced: true, ...scenarioMessage },
  setting: { namespaced: true, ...setting },
  site: { namespaced: true, ...site },
  staff: { namespaced: true, ...staff },
  streamRoute: { namespaced: true, ...streamRoute },
  survey: { namespaced: true, ...survey },
  system: { namespaced: true, ...system },
  tag: { namespaced: true, ...tag },
  template: { namespaced: true, ...template },
  user: { namespaced: true, ...user },
  variable: { namespaced: true, ...variable }
};