# fly.staging.toml
app = "hatamotohq-staging"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[build]
  [build.args]
    RAILS_ENV = "staging"

[env]
  PORT = "3000"
  RAILS_ENV = "staging"
  RAILS_LOG_TO_STDOUT = "true"
  RAILS_SERVE_STATIC_FILES = "true"
  
[experimental]
  auto_rollback = true

[mounts]
  source = "hatamotohq_staging_storage"
  destination = "/rails/storage"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["web"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 50
    soft_limit = 40
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "10s"
    tls_skip_verify = false

[processes]
  web = "bundle exec rails server -p $PORT -b 0.0.0.0"
  worker = "bundle exec sidekiq"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[deploy]
  release_command = "bundle exec rails db:migrate"